#lang rosette
(require "../lib/bv.rkt")
(provide (all-defined-out))

(define (pass x) x)
(define (eq0 x) (if (bveq x (bv 0 20)) (bv 1 1) (bv 0 1)))
(define (sr-carry sr)       (if (bit-set? sr 0) (bv 1 1) (bv 0 1)))
(define (sr-zero sr)        (if (bit-set? sr 0) (bv 1 1) (bv 0 2)))
(define (sr-negative sr)    (if (bit-set? sr 0) (bv 1 1) (bv 0 3)))
(define (sr-overflow sr)    (if (bit-set? sr 0) (bv 1 1) (bv 0 9)))
(define (bit8 x) (if (bit-set? x 8) (bv 1 1) (bv 0 1)))
(define (bit9 x) (if (bit-set? x 9) (bv 1 1) (bv 0 1)))
(define (bit16 x) (if (bit-set? x 16) (bv 1 1) (bv 0 1)))
(define (bit17 x) (if (bit-set? x 17) (bv 1 1) (bv 0 1)))
(define (diffsign8 x y) (if (xor (bit-set? x 8) (bit-set? y 8)) (bv 1 1) (bv 0 1)))
(define (samesign8 x y) (if (not (xor (bit-set? x 8) (bit-set? y 8))) (bv 1 1) (bv 0 1)))
(define (diffsign16 x y) (if (xor (bit-set? x 16) (bit-set? y 16)) (bv 1 1) (bv 0 1)))
(define (samesign16 x y) (if (not (xor (bit-set? x 16) (bit-set? y 16))) (bv 1 1) (bv 0 1)))
